name: Spectator2
version: ${project.version}
main: com.github.kinoko_team.spectator2.Spectator2
api-version: 1.17
authors: [ kinoko_team ]
commands:
  HideMe:
    description: HideMe.
    usage: /<command> [player]
    permission: op
    permission-message: You don't have <permission>
